14:48:35.983 [main] ERROR com.miya.masa.log.sample.MyClassTest - logs\foo.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

java.nio.file.FileSystemException: logs\foo.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[na:1.8.0_05]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[na:1.8.0_05]
	at java.nio.file.Files.deleteIfExists(Files.java:1162) ~[na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:47) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$1(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$3/3458906.accept(Unknown Source) [bin/:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [na:1.8.0_05]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [na:1.8.0_05]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$0(MyClassTest.java:38) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$1/20917169.accept(Unknown Source) [bin/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.setup(MyClassTest.java:38) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
14:48:35.984 [main] ERROR com.miya.masa.log.sample.MyClassTest - logs\logFile.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

java.nio.file.FileSystemException: logs\logFile.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[na:1.8.0_05]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[na:1.8.0_05]
	at java.nio.file.Files.deleteIfExists(Files.java:1162) ~[na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:47) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$1(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$3/3458906.accept(Unknown Source) [bin/:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [na:1.8.0_05]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [na:1.8.0_05]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$0(MyClassTest.java:38) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$1/20917169.accept(Unknown Source) [bin/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.setup(MyClassTest.java:38) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
14:48:35.990 [main] ERROR com.miya.masa.log.sample.MyClassTest - logs\logFile_2014-10-15-14-48-35.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

java.nio.file.FileSystemException: logs\logFile_2014-10-15-14-48-35.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[na:1.8.0_05]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[na:1.8.0_05]
	at java.nio.file.Files.deleteIfExists(Files.java:1162) ~[na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:47) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$1(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$3/3458906.accept(Unknown Source) [bin/:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [na:1.8.0_05]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [na:1.8.0_05]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$0(MyClassTest.java:38) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$1/20917169.accept(Unknown Source) [bin/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.setup(MyClassTest.java:38) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
14:48:35.994 [main] ERROR com.miya.masa.log.sample.MyClassTest - logs\mylog.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

java.nio.file.FileSystemException: logs\mylog.log: プロセスはファイルにアクセスできません。別のプロセスが使用中です。

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_05]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[na:1.8.0_05]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[na:1.8.0_05]
	at java.nio.file.Files.deleteIfExists(Files.java:1162) ~[na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:47) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$1(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$3/3458906.accept(Unknown Source) [bin/:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [na:1.8.0_05]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [na:1.8.0_05]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:45) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$0(MyClassTest.java:38) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$1/20917169.accept(Unknown Source) [bin/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.setup(MyClassTest.java:38) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
14:48:35.995 [main] ERROR com.miya.masa.log.sample.MyClassTest - logs
java.nio.file.DirectoryNotEmptyException: logs
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266) ~[na:1.8.0_05]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[na:1.8.0_05]
	at java.nio.file.Files.deleteIfExists(Files.java:1162) ~[na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.deleteFile(MyClassTest.java:47) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest.lambda$0(MyClassTest.java:38) [bin/:na]
	at com.miya.masa.log.sample.MyClassTest$$Lambda$1/20917169.accept(Unknown Source) [bin/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) [na:1.8.0_05]
	at com.miya.masa.log.sample.MyClassTest.setup(MyClassTest.java:38) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
